baseURL: "https://ananunesv.github.io/teste/"
languageCode: "pt-br"
title: "MDS - Documentação"

# Configurações básicas
disableKinds: ["taxonomy", "term"]
enableRobotsTXT: true

# Configurações para GitHub Pages
canonifyURLs: true
relativeURLs: false

# Menus com URLs corretas para produção
menu:
  main:
    - identifier: "home"
      name: "Home"
      url: "/teste/"
      weight: 1
    - identifier: "sprint"
      name: "Sprints"
      url: "/teste/sprint/"
      weight: 2
    - identifier: "arquitetura"
      name: "Arquitetura"
      url: "/teste/arquitetura/"
      weight: 3
